sonar.projectKey=z-abe
sonar.projectName=z-abe
sonar.host.url=http://localhost:9000
sonar.token=${SONAR_TOKEN}

sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/target/**,**/*.jar,**/.git/**

community.rust.clippy.reportPaths=reports/clippy.json
community.rust.lcov.reportPaths=coverage/lcov.sonar.info
